server:
  port: 9898
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/class_item?useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: "0926"
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  params: count
  reasonable: true
  support-methods-arguments: true